config/routes.rb
Rails.application.routes.draw do
  devise_for :users
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'home#index'
resources :recipes, only: [:show, :new, :create]
resources :cuisines, only: [:show, :new, :create]
resources :recipe_types, only:[:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
  validates :name, presence: {message: 'Você deve informar o nome da cozinha' }
  validates :name, :uniqueness => true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :recipe_type

  validates :title, :recipe_type_id, :difficulty,
     :cook_time, :ingredients,
     :method, presence: {message:
    'Você deve informar todos os dados da receita'}
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
  validates :name, presence: {message:'Você deve informar o nome do tipo de receita'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def show
    @cuisine = Cuisine.find(params[:id])
    @recipes = Recipe.new
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    cuisine_params = params.require(:cuisine).permit(:name)
    @cuisine = Cuisine.new(cuisine_params)

    if @cuisine.save
      redirect_to cuisine_path(@cuisine.id)
    else
      flash[:error] = @cuisine.errors.full_messages
      render :new
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  def show
    @recipe_type = RecipeType.find(params[:id])
    @recipe = Recipe.new
    if @recipe.save
      redirect_to recipe_path(recipe.id)
    else
      flash[:errors] = 'Nenhuma receita encontrada para este tipo de receitas'
    end
  end
  def new
    @recipe_type = RecipeType.new
  end
  def create
    recipe_type = params.require(:recipe_type).permit(:name)
    @recipe_type = RecipeType.new(recipe_type)

    if @recipe_type.save
      redirect_to recipe_type_path(@recipe_type.id)
    else
      flash[:errors] = @recipe_type.errors.full_messages
      render :new
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @cuisine = Cuisine.all
    @recipe_type = RecipeType.all
    @recipe = Recipe.new
  end

  def create
    recipe_params = params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id,
      :difficulty, :cook_time, :ingredients, :method)
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipe_path(@recipe.id)
    else
      flash[:error] = @recipe.errors.full_messages
      @cuisine = Cuisine.all
      @recipe_type = RecipeType.all
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/cuisines/new.html.erb
<%= flash[:error] %>
<%= @cuisine.errors.details[:name]%>
<%= form_for (@cuisine) do |cuisine|%>
  <%= cuisine.label :name, "Nome" %>
  <%= cuisine.text_field :name %>
  <%= cuisine.submit 'Enviar'%>
<% end %>

app/views/cuisines/show.html.erb
<h1><%= @cuisine.name %></h1>
<% if @cuisine.recipes.empty? %>
  <%= 'Nenhuma receita encontrada para este tipo de cozinha' %>
<% else %>
  <% @cuisine.recipes.each do |recipe| %>
    <h1><%= recipe.title %></h1>
    <ul>
      <li><%= recipe.recipe_type.name %></li>
      <li><%= recipe.cuisine.name %></li>
      <li><%= recipe.difficulty %></li>
      <li><%= recipe.cook_time %> minutos </li>
    </ul>
  <% end %>
<% end %>

app/views/home/index.html.erb
<h1> CookBook </h1>
<p>'Bem-vindo ao maior livro de receitas online'</p>

<%= link_to 'Enviar uma receita', new_recipe_path %>

<% @recipes.each do |recipe|%>
  <h1><%= link_to recipe.title, recipe_path(recipe.id) %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos </li>
  </ul>
<% end %>

<% @recipe_types.each do |recipe_type| %>
  <%= link_to recipe_type.name, recipe_type_path(recipe_type.id) %>
  <% end %>

<% @cuisines.each do |cuisine| %>
  <%= link_to cuisine.name, cuisine_path(cuisine.id)  %>
<% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCookbook2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipe_types/new.html.erb
<%= flash[:errors] %>
<%= form_for (@recipe_type) do |recipe_type| %>
  <%= recipe_type.label :name, 'Nome' %>
  <%= recipe_type.text_field :name %>
  <%= recipe_type.submit 'Enviar' %>
<% end %>

app/views/recipe_types/show.html.erb
<h1><%= @recipe_type.name %></h1>
<% if @recipe_type.recipes.empty? %>
     Nenhuma receita encontrada para este tipo de receitas
<% else %>
  <% @recipe_type.recipes.each do |recipe| %>
    <h1><%= recipe.title %></h1>
    <ul>
      <li><%= recipe.recipe_type.name %></li>
      <li><%= recipe.cuisine.name %></li>
      <li><%= recipe.difficulty %></li>
      <li><%= recipe.cook_time %> minutos </li>
    </ul>
  <% end %>
<% end %>

app/views/recipes/new.html.erb
<%= flash[:error] %>
<%= form_for(@recipe) do |recipe|  %>

  <div>
  <%=recipe.label :title, 'Título' %>
  <%=recipe.text_field :title  %>
  </div>
  <div>
  <%= recipe.label :recipe_type_id, 'Tipo da Receita'  %>
  <%= recipe.collection_select(:recipe_type_id, @recipe_type, :id, :name) %>
  </div>
  <div>
  <%= recipe.label :cuisine_id, 'Cozinha' %>
  <%= recipe.collection_select(:cuisine_id, @cuisine, :id, :name) %>
  </div>
  <div>
  <%= recipe.label :difficulty, 'Dificuldade' %>
  <%= recipe.text_field :difficulty %>
  </div>
  <div>
  <%= recipe.label :cook_time, 'Tempo de Preparo' %>
  <%= recipe.text_field :cook_time %>
  </div>
  <div>
  <%= recipe.label :ingredients, 'Ingredientes' %>
  <%= recipe.text_field :ingredients %>
  </div>
  <div>
  <%= recipe.label :method, 'Como Preparar' %>
  <%= recipe.text_field :method %>
  </div>
  <%= recipe.submit 'Enviar' %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>

<h3> Detalhes </h3>
<p><%= @recipe.recipe_type.name %> </p>
<p><%= @recipe.cuisine.name %> </p>
<p><%= @recipe.difficulty  %> </p>
<p><%= @recipe.cook_time %> minutos </p>
<h3> Ingredientes </h3>
<p><%= @recipe.ingredients %></p>
<h3> Como Preparar </h3>
<p><%= @recipe.method  %></p>

<%=link_to 'Voltar', root_path %>